path: /home/shakib/Documents/Live-Vehicle-Recognition-with-YOLO11/Dataset

train: train/images
test: test/images
val:  valid/images

# Classes
names:
  0: Ambulance
  1: Bus
  2: Car
  3: Motorcycle
  4: Truck

